export const URL = "http://localhost:3001"

export const REQUEST_CHARITIES = "REQUEST_CHARITIES"

export const REQUEST_PAYMENT = "REQUEST_PAYMENT"

export const DONATION_AMOUNT = "DONATION_AMOUNT"

export const SHOW_DONATION_AMOUNT_LIST = "SHOW_DONATION_AMOUNT_LIST"

export const UPDATE_DONATION_AMOUNT_LIST = "UPDATE_DONATION_AMOUNT_LIST"

export const PAY_NOW = "PAY_NOW"

export const UPDATE_MESSAGE = "UPDATE_MESSAGE"

export const UPDATE_TOTAL_DONATE = "UPDATE_TOTAL_DONATE"